name: LilyPad-Connect
version: ${build.number}
description: LilyPad

api-version: 1.14

author: LilyPad
website: http://www.lilypadmc.org/

load: STARTUP
loadbefore: [ProtocolLib, ProtocolSupport]
main: ${main.class}
