name: LilyPad-Connect
version: ${build.number}
description: LilyPad

api-version: '1.14'

author: LilyPad
website: http://www.lilypadmc.org/

load: STARTUP
softdepend: [ProtocolLib]
loadbefore: [ProtocolSupport]
main: ${main.class}